// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwNBASkDf2XIYK9lyNWT19ope6Pk_PKU',
    appId: '1:999932219761:web:805e5d944fe30d23b426d0',
    messagingSenderId: '999932219761',
    projectId: 'chatify-dea97',
    authDomain: 'chatify-dea97.firebaseapp.com',
    storageBucket: 'chatify-dea97.appspot.com',
    measurementId: 'G-WLSQ7H7W9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogROmg87BgTTNdF4c3NhoMkMv6W0YObk',
    appId: '1:999932219761:android:a6c2d0a04c1272adb426d0',
    messagingSenderId: '999932219761',
    projectId: 'chatify-dea97',
    storageBucket: 'chatify-dea97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_hmY5t5j8Lmhldo_4gEFLw_LQJVU2gk',
    appId: '1:999932219761:ios:fc7ae7cc98f0b968b426d0',
    messagingSenderId: '999932219761',
    projectId: 'chatify-dea97',
    storageBucket: 'chatify-dea97.appspot.com',
    iosClientId: '999932219761-h6lpmu76p36d4hhf24v30v01hpdvpcit.apps.googleusercontent.com',
    iosBundleId: 'com.etechviral.selfHostGroupChatApp',
  );
}
